routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
    
});

Route::resource('/employee', 'App\Http\Controllers\EmployeeController');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'address_id'
    ];

    public static function getEmployees() {
        $emp = \DB::select(\DB::raw("SELECT e.id, e.name, a.state, a.city FROM employees as e INNER JOIN addresses as a on e.address_id = a.id group by e.id"));
        return $emp;
    }

    public static function deleteEmployee(int $id) {
        $del = \DB::delete(\DB::raw("DELETE e, a, em FROM employees as e INNER JOIN addresses as a on e.address_id = a.id INNER JOIN emails as em on em.employee_id = e.id WHERE e.id = $id"));
        return $del;
    }

    public static function getEmployee(int $id) {
        $emp = \DB::select(\DB::raw("SELECT * FROM employees as e INNER JOIN addresses as a on  a.id = e.address_id  WHERE e.id = $id"))[0];
        return $emp;
    }

    public static function getContact(int $id){
        $contact = \DB::select(\DB::raw("SELECT * FROM mobile_number_whatsapp_numbers WHERE employee_id = $id AND is_whatsapp = 0 AND is_primary_wtsp = 0"));
        // dd($contact);
        return $contact;
    }

    public static function getWhatsapp(int $id) {
        $wtsp = \DB::select(\DB::raw("SELECT * FROM `mobile_number_whatsapp_numbers` WHERE employee_id = $id AND is_primary_mobile = 0 AND is_whatsapp = 1"));
        // dd($wtsp);
        return $wtsp;
    }

    public static function getEmail(int $id) {
        $email = \DB::select(\DB::raw("SELECT * FROM emails WHERE employee_id = $id"));
        // dd($email); 
        return $email;
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddEmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;
use App\Models\Address;
use App\Models\Employee;
use App\Models\Email;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    public function index()
    {
        
        
        // return view('/employee.index', compact([
        //     'employees'
        // ]));
        // redirect('employee.add');
        
        $employees = Employee::getEmployees();
        // dd($employees);
        return view('employee.index', [
            'employees' => $employees
        ]);
    }

    public function create()
    {
        return view('employee.add');
    }

    public function store(AddEmployeeRequest $request) {
        // dd($request);s
       
        $address = Address::create([
            'address 1' => $request->address1,
            'address 2' => $request->address2,
            'location' => $request->location,
            'zip' => $request->zip,
            'postal area' => $request->postal_area,
            'country' => $request->country,
            'state' => $request->state,
            'city' => $request->city,
            'district' => $request->district,
            'suburb' => $request->suburb,
            'taluka' => $request->taluka,
            'east/west' => $request->east_west
        ]);

        // dd($address->id);
        $emp = Employee::create([
            'name' => $request->name,
            'address_id' => $address->id
        ]);


        // dd($address->id);
        // dd($request->email); 
        for ($i = 0; $i < count($request->email); $i++)   
        {
            $email = \DB::table('emails')->insertGetId([
                'email_id' => $request->email[$i],
                'is_primary' => ($request->email[$i] === $request->email_radio)? 1 : 0,
                'employee_id' => $emp->id
            ]);
        }


        for ($i = 0; $i < count($request->whatsapp); $i++) {
            $arr = [];
            array_push($arr, $request->whatsapp[$i]);
           
        }

        for ($i = 0; $i < count($request->contact); $i++) {
            if (!(in_array($request->contact[$i], $request->whatsapp))) {
                array_push($arr, $request->contact[$i]);
            }
        }

        // dd( $request);

        $var = 0;
        for ($i = 0; $i < count($arr); $i++) {
            if ((in_array($arr[$i], $request->whatsapp))) {
                $var = 1;
            } else{
                $var = 0;
            }
            $number = \DB::table('mobile_number_whatsapp_numbers')->insertGetId([
                'mobile_number' => $arr[$i],
                'is_primary_mobile' => ($arr[$i] == $request->radio)? 1 : 0,
                'is_primary_wtsp' => ($arr[$i] == $request->wtsp_radio)? 1 : 0,
                'is_whatsapp' => $var,
                'employee_id' => $emp->id
            ]);
            
        }
        // dd($emp->id);

        $employees = Employee::getEmployees();
        return view('employee.index', compact([
            'employees'
        ]));

        
        
    }

    public function edit(int $id)
    {
        $emp = Employee::getEmployee($id);
        $contact = Employee::getContact($id);
        $wtsp = Employee::getWhatsapp($id);
        $emails = Employee::getEmail($id);
        return view('employee.edit', compact(['emp', 'contact', 'wtsp', 'emails']));
    }

    public function update(UpdateEmployeeRequest $request, int $id)
    {
        // dd($request->contact);
        
        $emp = \DB::table('employees')->where('id', $id)->update(['name' => $request->name]);
        $address_id = \DB::table('employees')->select("address_id")->where('id', $id)->get('address_id');
        // dd($request);
        $address = \DB::table('addresses')->where('id', $address_id[0]->address_id)->update([
            'address 1' => $request->address1,
            'address 2' => $request->address2,
            'location' => $request->location,
            'zip' => $request->zip,
            'postal area' => $request->postal_area,
            'country' => $request->country,
            'state' => $request->state,
            'city' => $request->city,
            'district' => $request->district,
            'suburb' => $request->suburb,
            'taluka' => $request->taluka,
            'east/west' => $request->east_west]);
        
        $contact = Employee::getContact($id);
        // $contact->sync($request->contact);
        // dd($contact);
        // dd($request->contact);
        $update_arr = [];
        $delete_arr = [];
        $create_arr = [];
        // dd($contact[0]->id);
        for ($i = 0; $i < count($request->contact); $i++) {
            
            for ($j = 0; $j < count($contact); $j++)
            {
                if (((int)$request->contact[$i]) == $contact[$j]->mobile_number && !in_array($contact[$i]->mobile_number, $update_arr)) {
                    array_push($update_arr, $contact[$i]->mobile_number);
                }
            }
        }
        // dd($update_arr);
        for ($i = 0; $i < count($request->contact); $i++) {

            for ($j = 0; $j < count($contact); $j++)
            {   
                // var_dump("for: " . $request->contact[$i]);
                // var_dump(in_array((int)$request->contact[$i], $update_arr)."===================");
                // var_dump(in_array((int)$request->contact[$i], $create_arr));
                if(((!  in_array((int)$request->contact[$i], $update_arr)) &&  (! in_array((int)$request->contact[$i], $create_arr))))
                {
                    array_push($create_arr, $request->contact[$i]);
                }
            }
        }
        
        for ($j = 0; $j < count($contact); $j++)
        {
            if (!(in_array($contact[$j]->id, $update_arr))) {
                array_push($delete_arr, $contact[$j]->mobile_number);
            }
        }


        // dd($create_arr);

        for ($j = 0; $j < count($delete_arr); $j++)
        {
            $del = \DB::table('mobile_number_whatsapp_numbers')->where('id', $delete_arr[$j])->delete();
        }
       
        for ($i = 0; $i < count($create_arr); $i++) {
            $number = \DB::table('mobile_number_whatsapp_numbers')->insertGetId([
                'mobile_number' => $create_arr[$i],
                'is_primary_mobile' => ($create_arr[$i] == $request->radio)? 1 : 0,
                'is_primary_wtsp' => 0,
                'is_whatsapp' => 0,
                'employee_id' => $id
            ]);
            // dd($number);
        }
        // dd($create_arr);

        for ($i = 0; $i < count($update_arr); $i++) {
            $no = \DB::table('mobile_number_whatsapp_numbers')->where('mobile_number', $update_arr[$i])->update([
                'is_primary_mobile' => ($update_arr[$i] == $request->radio)? 1 : 0,
                'is_primary_wtsp' => 0,
                'is_whatsapp' => 0,
                'employee_id' => $id
            ]);
            // dd($no);
        }

        // var_dump("u",$update_arr);
        // var_dump("c",$create_arr );
        // var_dump("del",$delete_arr);
        // dd("h");

        //wtsp
        $wtsp = Employee::getWhatsapp($id);
        $update_arr = [];
        $delete_arr = [];
        $create_arr = [];

        for ($i = 0; $i < count($request->whatsapp); $i++) {
            
            for ($j = 0; $j < count($wtsp); $j++)
            {
                if (((int)$request->whatsapp[$i]) == $wtsp[$j]->mobile_number) {
                    array_push($update_arr, $wtsp[$i]->mobile_number);
                }
            }
        }
        
        for ($i = 0; $i < count($request->whatsapp); $i++) {

            for ($j = 0; $j < count($wtsp); $j++)
            {   
                if(! in_array($request->whatsapp[$i], $update_arr) &&  ! in_array($request->whatsapp[$i], $create_arr))
                {
                    array_push($create_arr, $request->whatsapp[$i]);
                }
            }
        }
        
        for ($j = 0; $j < count($wtsp); $j++)
        {
            if (!(in_array($wtsp[$j]->id, $update_arr))) {
                array_push($delete_arr, $wtsp[$j]->mobile_number);
            }
        }
        // dd($delete_arr);
        
        for ($j = 0; $j < count($delete_arr); $j++)
        {
            $del = \DB::table('mobile_number_whatsapp_numbers')->where('id', $delete_arr[$j])->delete();
        }

        
       
        for ($i = 0; $i < count($create_arr); $i++) {
            $n = \DB::table('mobile_number_whatsapp_numbers')->insertGetId([
                'mobile_number' => $create_arr[$i],
                'is_primary_mobile' => 0,
                'is_primary_wtsp' => ($create_arr[$i] == $request->wtsp_radio)? 1 : 0,
                'is_whatsapp' => 1,
                'employee_id' => $id
            ]);
        }

        for ($i = 0; $i < count($update_arr); $i++) {
            $num = \DB::table('mobile_number_whatsapp_numbers')->where('mobile_number', $update_arr[$i])->update([
                'is_primary_mobile' => 0,
                'is_primary_wtsp' => ($update_arr[$i] == $request->wtsp_radio)? 1 : 0,
                'is_whatsapp' => 1,
                'employee_id' => $id
            ]);
        }

        //email
        $emails = Employee::getEmail($id);
        $update_arr = [];
        $delete_arr = [];
        $create_arr = [];
        // // dd($request);
        for ($i = 0; $i < count($request->email); $i++) {
            
            for ($j = 0; $j < count($emails); $j++)
            {
                if (($request->email[$i]) == $emails[$j]->email_id) {
                    array_push($update_arr, $emails[$i]->email_id);
                }
            }
        }
        
        for ($i = 0; $i < count($request->email); $i++) {

        for ($j = 0; $j < count($emails); $j++)
        {   

resources/views/employee/index.blade.php
@extends('layouts.app')
@section('page-level-styles')
    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
@endsection
@section('content')
<div class="container">
        <div class="row">
            <div class="col-md-12">
                
                <div class="d-flex justify-content-end mb-3 bg-back">
                    <a href="{{ route('employee.create') }}" class="btn btn-primary">Create Employee</a>
                </div>
            </div>
        </div>
        <table class="table table-striped" id="team-table">
                <thead>
                    <th>Name</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Actions</th>
                    
                </thead>
                <tbody>
                    @foreach($employees as $emp)
                    <tr >
                        <td>{{$emp->name}}</td> 
                        <td>{{$emp->city}}</td>
                        <td>{{$emp->state}}</td>
                        <td>
                                <a class="btn btn-primary btn-sm text-white" href="{{route('employee.edit', $emp->id)}}" ><i class="fa fa-pen"></i></a>
                                <a href="" class="btn btn-danger btn-sm" onclick="displayModalDelete({{$emp->id}})" data-toggle="modal" data-target="#deleteModal"><i class="fa fa-trash"></i></a>
                                <a class="btn btn-success btn-sm text-white" href=""><i class="fa fa-eye"></i></a>
                                </td>
                    </tr>
                    @endforeach
                    
                </tbody>
            </table>
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            
                <form action="" method="POST" id="deleteForm">
                    @csrf
                    @method('DELETE')
                <div class="modal-body">
                    <p>Are you sure want to delete Employee?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete Employee</button>
                </div>
          </div>
        </form>
        </div>
      </div>

</div>


@endsection

@section('page-level-styles')
    <style>
        .a-tag {
            text-decoration:none !important
        }
    </style>
@endsection
@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
<!--     <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready( function () {
            $('#team-table').DataTable({
                "lengthMenu": [5, 10, 20, "All"],
                "order": [
                    [1, "ASC"]
                ],
                "columnDefs": [{
                    'orderable': false,
                    'targets': [-1]
                }]
            });
        }); 

        
    </script> -->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>

    <script type="text/javascript">
        function displayModalDelete($id) {
            console.log($id);
            var url = 'employee/' + $id;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection